-- Generated by Matcha GUI Builder
local Mouse = game.Players.LocalPlayer:GetMouse()

-- Square1 (Square)
local Square1 = Drawing.new("Square")
Square1.Visible = true
Square1.Transparency = 1
Square1.ZIndex = 10
Square1.Color = Color3.fromHex("#121212")
Square1.Position = Vector2.new(9, 8)
Square1.Size = Vector2.new(233, 507)
Square1.Filled = true
Square1.Corner = 36

-- Slider3 (Slider)

-- Slider Slider3
local Slider3 = Drawing.new("Square")
Slider3.Visible = true
Slider3.Transparency = 1
Slider3.Color = Color3.fromHex("#444444")
Slider3.Filled = true
Slider3.Size = Vector2.new(189, 10)
Slider3.Position = Vector2.new(32, 183.5)
Slider3.ZIndex = 20
Slider3.Corner = 18
local Slider3_Value = 15
local Slider3_Knob = Drawing.new("Square")
Slider3_Knob.Visible = true
Slider3_Knob.Transparency = 1
Slider3_Knob.Color = Color3.fromHex("#ffffff")
Slider3_Knob.Filled = true
Slider3_Knob.Size = Vector2.new(20, 20)
Slider3_Knob.Position = Slider3.Position + Vector2.new(189 * 0.4827586206896552 - 10, 5 - 10)
Slider3_Knob.ZIndex = 21
Slider3_Knob.Corner = 100
local Slider3_ValueText = Drawing.new("Text")
Slider3_ValueText.Visible = true
Slider3_ValueText.Text = tostring(math.floor(Slider3_Value)) .. ""
Slider3_ValueText.Size = 16
Slider3_ValueText.Center = true
Slider3_ValueText.Outline = true
Slider3_ValueText.Color = Color3.new(1, 1, 1)
Slider3_ValueText.Position = Slider3.Position + Vector2.new(189/2, -10)
Slider3_ValueText.ZIndex = 22

-- Text5 (Text)
local Text5 = Drawing.new("Text")
Text5.Visible = true
Text5.Transparency = 1
Text5.ZIndex = 90
Text5.Color = Color3.fromHex("#ffffff")
Text5.Position = Square1.Position + Vector2.new(38, 24)
Text5.Text = "bad dh orbit"
Text5.Size = 27
Text5.Center = false
Text5.Outline = false
Text5.Font = Drawing.Fonts.UI

-- Square8 (Square)
local Square8 = Drawing.new("Square")
Square8.Visible = true
Square8.Transparency = 1
Square8.ZIndex = 40
Square8.Color = Color3.fromHex("#444444")
Square8.Position = Square1.Position + Vector2.new(18.5, 17)
Square8.Size = Vector2.new(203, 39)
Square8.Filled = true
Square8.Corner = 29

-- Intelligent Border for Square8
local Square8_Border = Drawing.new("Square")
Square8_Border.Visible = true
Square8_Border.Transparency = 1
Square8_Border.ZIndex = 41
Square8_Border.Color = Color3.fromHex("#000000")
Square8_Border.Filled = false
Square8_Border.Thickness = 0
Square8_Border.Position = Square8.Position
Square8_Border.Size = Square8.Size
Square8_Border.Corner = 29

-- Dropdown9 (Dropdown)
local Dropdown9 = Drawing.new("Square")
Dropdown9.Visible = true
Dropdown9.Transparency = 1
Dropdown9.Color = Color3.fromHex("#444444")
Dropdown9.Filled = true
Dropdown9.Size = Vector2.new(205, 32)
Dropdown9.Position = Vector2.new(21, 211.5)
Dropdown9.ZIndex = 999
Dropdown9.Corner = 16
local Dropdown9_Text = Drawing.new("Text")
Dropdown9_Text.Visible = true
Dropdown9_Text.Text = "select player (press)"
Dropdown9_Text.Size = 16
Dropdown9_Text.Outline = false
Dropdown9_Text.Font = 0
Dropdown9_Text.Color = Color3.fromHex("#ffffff")
Dropdown9_Text.Position = Dropdown9.Position + Vector2.new(5, 8)
Dropdown9_Text.ZIndex = 1000
local Dropdown9_Arrow = Drawing.new("Text")
Dropdown9_Arrow.Visible = true
Dropdown9_Arrow.Text = "▼"
Dropdown9_Arrow.Size = 12.8
Dropdown9_Arrow.Outline = false
Dropdown9_Arrow.Color = Color3.fromHex("#ffffff")
Dropdown9_Arrow.Position = Dropdown9.Position + Vector2.new(205 - 20, 8)
Dropdown9_Arrow.ZIndex = 1000
local Dropdown9_Items = {}

-- Switch12 (Switch)
local Switch12 = Drawing.new("Switch")
Switch12.Visible = true
Switch12.Transparency = 1
Switch12.ZIndex = 100
Switch12.Color = Color3.fromHex("#ffffff")
Switch12.Position = Square1.Position + Vector2.new(13.5, 280)

-- Switch Switch12
local Switch12_IsChecked = false
local Switch12 = Drawing.new("Square")
Switch12.Visible = true
Switch12.Transparency = 1
Switch12.Color = Color3.fromHex("#000000")
Switch12.Thickness = 1
Switch12.Filled = false
Switch12.Size = Vector2.new(40, 26)
Switch12.Position = Vector2.new(22.5, 288)
Switch12.ZIndex = 100
Switch12.Corner = 18
local Switch12_Bg = Drawing.new("Square")
Switch12_Bg.Visible = true
Switch12_Bg.Transparency = 1
Switch12_Bg.Color = Color3.fromHex("#ffffff")
Switch12_Bg.Filled = true
Switch12_Bg.Size = Switch12.Size
Switch12_Bg.Position = Switch12.Position
Switch12_Bg.ZIndex = 100
Switch12_Bg.Corner = 18
local Switch12_IndBorder = Drawing.new("Square")
Switch12_IndBorder.Visible = true
Switch12_IndBorder.Transparency = 1
Switch12_IndBorder.Color = Color3.fromHex("#000000")
Switch12_IndBorder.Thickness = 1
Switch12_IndBorder.Filled = false
Switch12_IndBorder.Size = Vector2.new(24, 24)
Switch12_IndBorder.ZIndex = 102
Switch12_IndBorder.Corner = 18
local Switch12_Ind = Drawing.new("Square")
Switch12_Ind.Visible = true
Switch12_Ind.Transparency = 1
Switch12_Ind.Color = Color3.fromHex("#444444")
Switch12_Ind.Filled = true
Switch12_Ind.Size = Vector2.new(24, 24)
Switch12_Ind.ZIndex = 102
Switch12_Ind.Corner = 18
Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
local Switch12_Label = Drawing.new("Text")
Switch12_Label.Visible = true
Switch12_Label.Text = "orbit"
Switch12_Label.Size = 16
Switch12_Label.Color = Color3.fromHex("#FFFFFF")
Switch12_Label.Outline = true
Switch12_Label.Font = Drawing.Fonts.UI
Switch12_Label.Position = Switch12.Position + Vector2.new(50, 5)
Switch12_Label.ZIndex = 101

-- Text13 (Text)
local Text13 = Drawing.new("Text")
Text13.Visible = true
Text13.Transparency = 1
Text13.ZIndex = 140
Text13.Color = Color3.fromHex("#FFFFFF")
Text13.Position = Square1.Position + Vector2.new(64.5, 134)
Text13.Text = "tp distance"
Text13.Size = 18
Text13.Center = false
Text13.Outline = false
Text13.Font = Drawing.Fonts.UI

-- Square14 (Square)
local Square14 = Drawing.new("Square")
Square14.Visible = true
Square14.Transparency = 1
Square14.ZIndex = 50
Square14.Color = Color3.fromHex("#444444")
Square14.Position = Square1.Position + Vector2.new(19, 134)
Square14.Size = Vector2.new(202, 19)
Square14.Filled = true
Square14.Corner = 29

-- Intelligent Border for Square14
local Square14_Border = Drawing.new("Square")
Square14_Border.Visible = true
Square14_Border.Transparency = 1
Square14_Border.ZIndex = 51
Square14_Border.Color = Color3.fromHex("#000000")
Square14_Border.Filled = false
Square14_Border.Thickness = 0
Square14_Border.Position = Square14.Position
Square14_Border.Size = Square14.Size
Square14_Border.Corner = 29

-- Square15 (Square)
local Square15 = Drawing.new("Square")
Square15.Visible = true
Square15.Transparency = 1
Square15.ZIndex = 70
Square15.Color = Color3.fromHex("#444444")
Square15.Position = Square1.Position + Vector2.new(13.5, 250)
Square15.Size = Vector2.new(202, 19)
Square15.Filled = true
Square15.Corner = 29

-- Intelligent Border for Square15
local Square15_Border = Drawing.new("Square")
Square15_Border.Visible = true
Square15_Border.Transparency = 1
Square15_Border.ZIndex = 71
Square15_Border.Color = Color3.fromHex("#000000")
Square15_Border.Filled = false
Square15_Border.Thickness = 0
Square15_Border.Position = Square15.Position
Square15_Border.Size = Square15.Size
Square15_Border.Corner = 29

-- Text16 (Text)
local Text16 = Drawing.new("Text")
Text16.Visible = true
Text16.Transparency = 1
Text16.ZIndex = 160
Text16.Color = Color3.fromHex("#FFFFFF")
Text16.Position = Square1.Position + Vector2.new(81, 250)
Text16.Text = "toggles"
Text16.Size = 18
Text16.Center = false
Text16.Outline = false
Text16.Font = Drawing.Fonts.UI

-- Keybind17 (Keybind)

-- Keybind Keybind17
local Keybind17 = Drawing.new("Square")
Keybind17.Visible = true
Keybind17.Transparency = 1
Keybind17.Color = Color3.fromHex("#444444")
Keybind17.Filled = true
Keybind17.Size = Vector2.new(100, 30)
Keybind17.Position = Vector2.new(124.5, 288)
Keybind17.ZIndex = 180
Keybind17.Corner = 10
local Keybind17_Text = Drawing.new("Text")
Keybind17_Text.Text = "[ X ]"
Keybind17_Text.Size = 16
Keybind17_Text.Center = true
Keybind17_Text.Outline = false
Keybind17_Text.Font = Drawing.Fonts.UI
Keybind17_Text.Color = Color3.fromHex("#ffffff")
Keybind17_Text.Position = Keybind17.Position + Vector2.new(100/2, 30/2)
Keybind17_Text.Visible = true
Keybind17_Text.ZIndex = 182
local Keybind17_Key = 0x58
local Keybind17_IsListening = false

-- Switch21 (Switch)
local Switch21 = Drawing.new("Switch")
Switch21.Visible = true
Switch21.Transparency = 1
Switch21.ZIndex = 110
Switch21.Color = Color3.fromHex("#ffffff")
Switch21.Position = Square1.Position + Vector2.new(12, 321)

-- Switch Switch21
local Switch21_IsChecked = false
local Switch21 = Drawing.new("Square")
Switch21.Visible = true
Switch21.Transparency = 1
Switch21.Color = Color3.fromHex("#000000")
Switch21.Thickness = 1
Switch21.Filled = false
Switch21.Size = Vector2.new(40, 26)
Switch21.Position = Vector2.new(21, 329)
Switch21.ZIndex = 110
Switch21.Corner = 18
local Switch21_Bg = Drawing.new("Square")
Switch21_Bg.Visible = true
Switch21_Bg.Transparency = 1
Switch21_Bg.Color = Color3.fromHex("#ffffff")
Switch21_Bg.Filled = true
Switch21_Bg.Size = Switch21.Size
Switch21_Bg.Position = Switch21.Position
Switch21_Bg.ZIndex = 110
Switch21_Bg.Corner = 18
local Switch21_IndBorder = Drawing.new("Square")
Switch21_IndBorder.Visible = true
Switch21_IndBorder.Transparency = 1
Switch21_IndBorder.Color = Color3.fromHex("#000000")
Switch21_IndBorder.Thickness = 1
Switch21_IndBorder.Filled = false
Switch21_IndBorder.Size = Vector2.new(24, 24)
Switch21_IndBorder.ZIndex = 112
Switch21_IndBorder.Corner = 18
local Switch21_Ind = Drawing.new("Square")
Switch21_Ind.Visible = true
Switch21_Ind.Transparency = 1
Switch21_Ind.Color = Color3.fromHex("#444444")
Switch21_Ind.Filled = true
Switch21_Ind.Size = Vector2.new(24, 24)
Switch21_Ind.ZIndex = 112
Switch21_Ind.Corner = 18
Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
local Switch21_Label = Drawing.new("Text")
Switch21_Label.Visible = true
Switch21_Label.Text = "void"
Switch21_Label.Size = 16
Switch21_Label.Color = Color3.fromHex("#FFFFFF")
Switch21_Label.Outline = true
Switch21_Label.Font = Drawing.Fonts.UI
Switch21_Label.Position = Switch21.Position + Vector2.new(50, 5)
Switch21_Label.ZIndex = 111

-- Keybind22 (Keybind)

-- Keybind Keybind22
local Keybind22 = Drawing.new("Square")
Keybind22.Visible = true
Keybind22.Transparency = 1
Keybind22.Color = Color3.fromHex("#444444")
Keybind22.Filled = true
Keybind22.Size = Vector2.new(100, 30)
Keybind22.Position = Vector2.new(124.5, 329)
Keybind22.ZIndex = 190
Keybind22.Corner = 10
local Keybind22_Text = Drawing.new("Text")
Keybind22_Text.Text = "[ V ]"
Keybind22_Text.Size = 16
Keybind22_Text.Center = true
Keybind22_Text.Outline = false
Keybind22_Text.Font = Drawing.Fonts.UI
Keybind22_Text.Color = Color3.fromHex("#ffffff")
Keybind22_Text.Position = Keybind22.Position + Vector2.new(100/2, 30/2)
Keybind22_Text.Visible = true
Keybind22_Text.ZIndex = 192
local Keybind22_Key = 0x56
local Keybind22_IsListening = false

-- Square23 (Square)
local Square23 = Drawing.new("Square")
Square23.Visible = true
Square23.Transparency = 1
Square23.ZIndex = 60
Square23.Color = Color3.fromHex("#444444")
Square23.Position = Square1.Position + Vector2.new(20, 64)
Square23.Size = Vector2.new(202, 19)
Square23.Filled = true
Square23.Corner = 29

-- Intelligent Border for Square23
local Square23_Border = Drawing.new("Square")
Square23_Border.Visible = true
Square23_Border.Transparency = 1
Square23_Border.ZIndex = 61
Square23_Border.Color = Color3.fromHex("#000000")
Square23_Border.Filled = false
Square23_Border.Thickness = 0
Square23_Border.Position = Square23.Position
Square23_Border.Size = Square23.Size
Square23_Border.Corner = 29

-- Text24 (Text)
local Text24 = Drawing.new("Text")
Text24.Visible = true
Text24.Transparency = 1
Text24.ZIndex = 150
Text24.Color = Color3.fromHex("#FFFFFF")
Text24.Position = Square1.Position + Vector2.new(64.5, 64)
Text24.Text = "orbit speed"
Text24.Size = 18
Text24.Center = false
Text24.Outline = false
Text24.Font = Drawing.Fonts.UI

-- Slider25 (Slider)

-- Slider Slider25
local Slider25 = Drawing.new("Square")
Slider25.Visible = true
Slider25.Transparency = 1
Slider25.Color = Color3.fromHex("#444444")
Slider25.Filled = true
Slider25.Size = Vector2.new(189, 10)
Slider25.Position = Vector2.new(34.5, 117.5)
Slider25.ZIndex = 30
Slider25.Corner = 18
local Slider25_Value = 0
local Slider25_Knob = Drawing.new("Square")
Slider25_Knob.Visible = true
Slider25_Knob.Transparency = 1
Slider25_Knob.Color = Color3.fromHex("#ffffff")
Slider25_Knob.Filled = true
Slider25_Knob.Size = Vector2.new(20, 20)
Slider25_Knob.Position = Slider25.Position + Vector2.new(189 * 0 - 10, 5 - 10)
Slider25_Knob.ZIndex = 31
Slider25_Knob.Corner = 100
local Slider25_ValueText = Drawing.new("Text")
Slider25_ValueText.Visible = true
Slider25_ValueText.Text = tostring(math.floor(Slider25_Value)) .. ""
Slider25_ValueText.Size = 16
Slider25_ValueText.Center = true
Slider25_ValueText.Outline = true
Slider25_ValueText.Color = Color3.new(1, 1, 1)
Slider25_ValueText.Position = Slider25.Position + Vector2.new(189/2, -10)
Slider25_ValueText.ZIndex = 32

-- Switch28 (Switch)
local Switch28 = Drawing.new("Switch")
Switch28.Visible = true
Switch28.Transparency = 1
Switch28.ZIndex = 120
Switch28.Color = Color3.fromHex("#ffffff")
Switch28.Position = Square1.Position + Vector2.new(12, 362)

-- Switch Switch28
local Switch28_IsChecked = false
local Switch28 = Drawing.new("Square")
Switch28.Visible = true
Switch28.Transparency = 1
Switch28.Color = Color3.fromHex("#000000")
Switch28.Thickness = 1
Switch28.Filled = false
Switch28.Size = Vector2.new(40, 26)
Switch28.Position = Vector2.new(21, 370)
Switch28.ZIndex = 120
Switch28.Corner = 18
local Switch28_Bg = Drawing.new("Square")
Switch28_Bg.Visible = true
Switch28_Bg.Transparency = 1
Switch28_Bg.Color = Color3.fromHex("#ffffff")
Switch28_Bg.Filled = true
Switch28_Bg.Size = Switch28.Size
Switch28_Bg.Position = Switch28.Position
Switch28_Bg.ZIndex = 120
Switch28_Bg.Corner = 18
local Switch28_IndBorder = Drawing.new("Square")
Switch28_IndBorder.Visible = true
Switch28_IndBorder.Transparency = 1
Switch28_IndBorder.Color = Color3.fromHex("#000000")
Switch28_IndBorder.Thickness = 1
Switch28_IndBorder.Filled = false
Switch28_IndBorder.Size = Vector2.new(24, 24)
Switch28_IndBorder.ZIndex = 122
Switch28_IndBorder.Corner = 18
local Switch28_Ind = Drawing.new("Square")
Switch28_Ind.Visible = true
Switch28_Ind.Transparency = 1
Switch28_Ind.Color = Color3.fromHex("#444444")
Switch28_Ind.Filled = true
Switch28_Ind.Size = Vector2.new(24, 24)
Switch28_Ind.ZIndex = 122
Switch28_Ind.Corner = 18
Switch28_IndBorder.Position = Switch28.Position + Vector2.new(1, 1)
Switch28_Ind.Position = Switch28.Position + Vector2.new(1, 1)
local Switch28_Label = Drawing.new("Text")
Switch28_Label.Visible = true
Switch28_Label.Text = "stomp"
Switch28_Label.Size = 16
Switch28_Label.Color = Color3.fromHex("#FFFFFF")
Switch28_Label.Outline = true
Switch28_Label.Font = Drawing.Fonts.UI
Switch28_Label.Position = Switch28.Position + Vector2.new(50, 5)
Switch28_Label.ZIndex = 121

-- Keybind29 (Keybind)

-- Keybind Keybind29
local Keybind29 = Drawing.new("Square")
Keybind29.Visible = true
Keybind29.Transparency = 1
Keybind29.Color = Color3.fromHex("#444444")
Keybind29.Filled = true
Keybind29.Size = Vector2.new(100, 30)
Keybind29.Position = Vector2.new(123, 370)
Keybind29.ZIndex = 200
Keybind29.Corner = 10
local Keybind29_Text = Drawing.new("Text")
Keybind29_Text.Text = "[ X ]"
Keybind29_Text.Size = 16
Keybind29_Text.Center = true
Keybind29_Text.Outline = false
Keybind29_Text.Font = Drawing.Fonts.UI
Keybind29_Text.Color = Color3.fromHex("#ffffff")
Keybind29_Text.Position = Keybind29.Position + Vector2.new(100/2, 30/2)
Keybind29_Text.Visible = true
Keybind29_Text.ZIndex = 202
local Keybind29_Key = 0x58
local Keybind29_IsListening = false

-- Keybind30 (Keybind)

-- Keybind Keybind30
local Keybind30 = Drawing.new("Square")
Keybind30.Visible = true
Keybind30.Transparency = 1
Keybind30.Color = Color3.fromHex("#444444")
Keybind30.Filled = true
Keybind30.Size = Vector2.new(100, 30)
Keybind30.Position = Vector2.new(70, 467)
Keybind30.ZIndex = 220
Keybind30.Corner = 21
local Keybind30_Text = Drawing.new("Text")
Keybind30_Text.Text = "[ Backspace ]"
Keybind30_Text.Size = 16
Keybind30_Text.Center = true
Keybind30_Text.Outline = true
Keybind30_Text.Font = Drawing.Fonts.UI
Keybind30_Text.Color = Color3.fromHex("#ffffff")
Keybind30_Text.Position = Keybind30.Position + Vector2.new(100/2, 30/2)
Keybind30_Text.Visible = true
Keybind30_Text.ZIndex = 222
local Keybind30_Key = 0x8
local Keybind30_IsListening = false

-- Text31 (Text)
local Text31 = Drawing.new("Text")
Text31.Visible = true
Text31.Transparency = 1
Text31.ZIndex = 170
Text31.Color = Color3.fromHex("#FFFFFF")
Text31.Position = Square1.Position + Vector2.new(64.5, 435)
Text31.Text = "menu keybind"
Text31.Size = 18
Text31.Center = false
Text31.Outline = false
Text31.Font = Drawing.Fonts.UI

-- Square32 (Square)
local Square32 = Drawing.new("Square")
Square32.Visible = true
Square32.Transparency = 1
Square32.ZIndex = 80
Square32.Color = Color3.fromHex("#444444")
Square32.Position = Square1.Position + Vector2.new(10, 434)
Square32.Size = Vector2.new(202, 19)
Square32.Filled = true
Square32.Corner = 29

-- Intelligent Border for Square32
local Square32_Border = Drawing.new("Square")
Square32_Border.Visible = true
Square32_Border.Transparency = 1
Square32_Border.ZIndex = 81
Square32_Border.Color = Color3.fromHex("#000000")
Square32_Border.Filled = false
Square32_Border.Thickness = 0
Square32_Border.Position = Square32.Position
Square32_Border.Size = Square32.Size
Square32_Border.Corner = 29

local KeyNames = {
    [48] = "0", [49] = "1", [50] = "2", [51] = "3", [52] = "4", [53] = "5", [54] = "6", [55] = "7", [56] = "8", [57] = "9",
    [1] = "LeftMouse", [2] = "RightMouse", [4] = "MiddleMouse",
    [8] = "Backspace", [9] = "Tab", [13] = "Enter", [16] = "Shift", [17] = "Ctrl", [18] = "Alt",
    [19] = "Pause", [20] = "CapsLock", [27] = "Esc", [32] = "Space",
    [33] = "PageUp", [34] = "PageDown", [35] = "End", [36] = "Home",
    [37] = "Left", [38] = "Up", [39] = "Right", [40] = "Down",
    [45] = "Insert", [46] = "Delete",
    [65] = "A", [66] = "B", [67] = "C", [68] = "D", [69] = "E", [70] = "F", [71] = "G", [72] = "H", [73] = "I", [74] = "J",
    [75] = "K", [76] = "L", [77] = "M", [78] = "N", [79] = "O", [80] = "P", [81] = "Q", [82] = "R", [83] = "S", [84] = "T",
    [85] = "U", [86] = "V", [87] = "W", [88] = "X", [89] = "Y", [90] = "Z",
    [112] = "F1", [113] = "F2", [114] = "F3", [115] = "F4", [116] = "F5", [117] = "F6", [118] = "F7", [119] = "F8",
    [120] = "F9", [121] = "F10", [122] = "F11", [123] = "F12",
}

local targetPlayer = nil
local orbitEnabled = false
local autoStompEnabled = false
local manualVoidEnabled = false
local teleporting = false
local autoVoidActive = false
local player = game:GetService("Players").LocalPlayer
local lastKnownTargetPosition = nil
local lastKnownTarget = nil
local lastKnownTargetName = nil
local dragging = nil
local dragStart = nil
local startPos = nil
local lastMouse1 = false
local voidStartPosition = nil
local orbitStartPosition = nil
local lastStompTime = 0
local stompActive = false
local stompEndTime = 0
local orbitActive = false

function speedToPercent(speed)
    local maxSpeed = 0.1
    return speed / maxSpeed
end

function percentToSpeed(percent)
    local maxSpeed = 0.1
    return percent * maxSpeed
end

function pressEKey()
    keypress(0x45)
    task.wait(0.05)
    keyrelease(0x45)
end

function returnToStartPosition()
    local character = player.Character
    if character and character:FindFirstChild("HumanoidRootPart") and orbitStartPosition then
        pcall(function()
            character.HumanoidRootPart.Position = orbitStartPosition
        end)
        notify("returned to start", "orbit", 5)
    end
end

function returnToVoidStartPosition()
    local character = player.Character
    if character and character:FindFirstChild("HumanoidRootPart") and voidStartPosition then
        pcall(function()
            character.HumanoidRootPart.Position = voidStartPosition
        end)
        voidStartPosition = nil
        notify("returned from void", "void", 5)
    end
end

function stopOrbitAndReturn(reason)
    if orbitEnabled or orbitActive then
        orbitEnabled = false
        orbitActive = false
        teleporting = false
        Switch12_IsChecked = false
        Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
        Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
        returnToStartPosition()
        if reason then
            notify(reason, "orbit", 5)
        end
    end
end

function sortPlayersAlphabetically(players)
    local playerNames = {}
    for _, plr in ipairs(players) do
        if plr ~= player then
            table.insert(playerNames, plr.Name)
        end
    end
    table.sort(playerNames, function(a, b)
        return a:lower() < b:lower()
    end)
    
    local sortedPlayers = {}
    for _, name in ipairs(playerNames) do
        for _, plr in ipairs(players) do
            if plr.Name == name then
                table.insert(sortedPlayers, plr)
                break
            end
        end
    end
    return sortedPlayers
end

task.spawn(function()
    while true do
        task.wait(1)
        local dropdownOpen = false
        if Dropdown9_Items[1] and Dropdown9_Items[1].Box then
            dropdownOpen = Dropdown9_Items[1].Box.Visible
        end
        
        if not dropdownOpen then
            for _, item in ipairs(Dropdown9_Items) do
                if item.Box then item.Box:Remove() end
                if item.Text then item.Text:Remove() end
            end
            Dropdown9_Items = {}
            
            local allPlayers = game:GetService("Players"):GetPlayers()
            local sortedPlayers = sortPlayersAlphabetically(allPlayers)
            
            local selectBox = Drawing.new("Square")
            selectBox.Visible = false
            selectBox.Transparency = 1
            selectBox.Color = Color3.fromHex("#333333")
            selectBox.Filled = true
            selectBox.Size = Vector2.new(205, 32)
            selectBox.Position = Dropdown9.Position + Vector2.new(0, 32)
            selectBox.ZIndex = 1000
            selectBox.Corner = 16
            local selectText = Drawing.new("Text")
            selectText.Visible = false
            selectText.Text = "select player (press)"
            selectText.Size = 16
            selectText.Outline = false
            selectText.Font = Drawing.Fonts.UI
            selectText.Color = Color3.fromHex("#FFFFFF")
            selectText.Position = selectBox.Position + Vector2.new(5, 8)
            selectText.ZIndex = 1001
            table.insert(Dropdown9_Items, {Box = selectBox, Text = selectText, Value = "select player (press)"})
            
            for _, plr in ipairs(sortedPlayers) do
                if plr ~= player then
                    local box = Drawing.new("Square")
                    box.Visible = false
                    box.Transparency = 1
                    box.Color = Color3.fromHex("#333333")
                    box.Filled = true
                    box.Size = Vector2.new(205, 32)
                    box.Position = Dropdown9.Position + Vector2.new(0, 32 * (#Dropdown9_Items + 1))
                    box.ZIndex = 1000
                    box.Corner = 16
                    local text = Drawing.new("Text")
                    text.Visible = false
                    text.Text = plr.Name
                    text.Size = 16
                    text.Outline = false
                    text.Font = Drawing.Fonts.UI
                    text.Color = Color3.fromHex("#FFFFFF")
                    text.Position = box.Position + Vector2.new(5, 8)
                    text.ZIndex = 1001
                    table.insert(Dropdown9_Items, {Box = box, Text = text, Value = plr.Name, Player = plr})
                end
            end
        end
    end
end)

function getPlayerStatus(plr)
    if not plr or not plr.Character then return "no char" end
    local bodyEffects = plr.Character:FindFirstChild("BodyEffects")
    if not bodyEffects then return "no body" end
    
    local koValue = bodyEffects:FindFirstChild("K.O")
    local deadValue = bodyEffects:FindFirstChild("Dead")
    local sDeathValue = bodyEffects:FindFirstChild("SDeath")
    
    if not koValue or not deadValue then return "no vals" end
    
    if deadValue.Value or (sDeathValue and sDeathValue.Value) then
        return "dead"
    elseif koValue.Value then
        return "ko"
    else
        return "alive"
    end
end

function getTorsoPosition(plr)
    if not plr or not plr.Character then return nil end
    
    local torso = plr.Character:FindFirstChild("UpperTorso")
    if not torso then
        torso = plr.Character:FindFirstChild("Torso")
    end
    if not torso then
        torso = plr.Character:FindFirstChild("LowerTorso")
    end
    if not torso then
        torso = plr.Character:FindFirstChild("HumanoidRootPart")
    end
    
    if torso then
        return torso.Position
    end
    return nil
end

function hasSpawnProtection(plr)
    if not plr or not plr.Character then return false end
    local character = plr.Character
    if character:FindFirstChildOfClass("ForceField") then
        return true
    end
    return false
end

function shouldAutoVoid()
    if targetPlayer and hasSpawnProtection(targetPlayer) then
        return true, "spawn protection"
    end
    local character = player.Character
    if character then
        local humanoid = character:FindFirstChild("Humanoid")
        if humanoid and humanoid.Health < 30 then
            return true, "health below 30"
        end
    end
    return false, nil
end

function getRandomOrbitPoint(center, radius)
    local x = (math.random() * 2 - 1) * radius
    local y = (math.random() * 2 - 1) * radius
    local z = (math.random() * 2 - 1) * radius
    return Vector3.new(center.X + x, center.Y + y, center.Z + z)
end

function teleportToTargetTorso()
    if not targetPlayer or not targetPlayer.Character then return end
    local targetPos = getTorsoPosition(targetPlayer)
    if not targetPos then return end
    
    local character = player.Character
    if not character or not character:FindFirstChild("HumanoidRootPart") then return end
    
    local hrp = character.HumanoidRootPart
    hrp.Position = Vector3.new(targetPos.X, targetPos.Y + 2.5, targetPos.Z)
end

function startOrbit()
    if not targetPlayer then
        notify("no target selected", "orbit", 5)
        orbitEnabled = false
        Switch12_IsChecked = false
        Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
        Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
        return
    end
    
    local targetStillExists = false
    for _, plr in ipairs(game:GetService("Players"):GetPlayers()) do
        if plr.Name == targetPlayer.Name then
            targetStillExists = true
            targetPlayer = plr
            break
        end
    end
    
    if not targetStillExists then
        notify("target left the game", "orbit", 5)
        stopOrbitAndReturn()
        return
    end
    
    local character = player.Character
    if character and character:FindFirstChild("HumanoidRootPart") and orbitStartPosition == nil then
        orbitStartPosition = character.HumanoidRootPart.Position
    end
    
    teleporting = true
    orbitActive = true
    lastKnownTarget = targetPlayer
    lastKnownTargetName = targetPlayer.Name
    
    if not character or not character:FindFirstChild("HumanoidRootPart") then
        teleporting = false
        return
    end
    
    local humanoidRootPart = character.HumanoidRootPart
    notify("orbit started", "orbit", 5)
    
    task.spawn(function()
        while teleporting and orbitEnabled and orbitActive do
            local targetExists = false
            for _, plr in ipairs(game:GetService("Players"):GetPlayers()) do
                if plr.Name == lastKnownTargetName then
                    targetExists = true
                    if targetPlayer ~= plr then
                        targetPlayer = plr
                    end
                    break
                end
            end
            
            if not targetExists then
                stopOrbitAndReturn("target left - returning")
                break
            end
            
            if not targetPlayer then
                stopOrbitAndReturn("target lost - returning")
                break
            end
            
            local status = "no char"
            if targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
                status = getPlayerStatus(targetPlayer)
            end
            
            local voidReason
            autoVoidActive, voidReason = shouldAutoVoid()
            
            if autoVoidActive then
                teleporting = false
                orbitActive = false
                notify(voidReason, "void", 5)
                task.spawn(function()
                    startVoid(true)
                end)
                break
            end
            
            if autoStompEnabled then
                if status == "ko" then
                    local targetPos = getTorsoPosition(targetPlayer)
                    if targetPos then
                        humanoidRootPart.Position = Vector3.new(targetPos.X, targetPos.Y + 2.5, targetPos.Z)
                        pressEKey()
                        stompActive = true
                        stompEndTime = tick() + 0.05
                        
                        while stompActive and tick() < stompEndTime do
                            if targetPlayer and targetPlayer.Character then
                                if getPlayerStatus(targetPlayer) == "dead" then
                                    stompActive = false
                                    teleporting = false
                                    orbitActive = false
                                    notify("dead - void activated", "void", 5)
                                    task.spawn(function()
                                        startVoid(true)
                                    end)
                                    break
                                end
                            end
                            task.wait(0.01)
                        end
                        stompActive = false
                    end
                    
                elseif status == "dead" then
                    teleporting = false
                    orbitActive = false
                    notify("target dead - void activated", "void", 5)
                    task.spawn(function()
                        startVoid(true)
                    end)
                    break
                end
            end
            
            if status == "alive" and not stompActive then
                if targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
                    local targetHRP = targetPlayer.Character.HumanoidRootPart
                    local targetPos = targetHRP.Position
                    lastKnownTargetPosition = targetPos
                    lastKnownTarget = targetPlayer
                    lastKnownTargetName = targetPlayer.Name
                    local newPos = getRandomOrbitPoint(targetPos, Slider3_Value)
                    humanoidRootPart.Position = newPos
                end
            end
            
            if Slider25_Value <= 0 then
                task.wait()
            else
                task.wait(Slider25_Value)
            end
        end
        
        teleporting = false
        orbitActive = false
    end)
end

function startVoid(isAutoVoid)
    local character = player.Character
    if not character or not character:FindFirstChild("HumanoidRootPart") then
        return
    end
    
    local humanoidRootPart = character.HumanoidRootPart
    if not isAutoVoid then
        if voidStartPosition == nil then
            voidStartPosition = humanoidRootPart.Position
        end
    end
    
    task.spawn(function()
        local voidActive = true
        
        while voidActive do
            if isAutoVoid then
                local shouldStillVoid, voidReason = shouldAutoVoid()
                local targetValid = false
                local status = "no target"
                
                if lastKnownTargetName then
                    for _, plr in ipairs(game:GetService("Players"):GetPlayers()) do
                        if plr.Name == lastKnownTargetName then
                            targetValid = true
                            if targetPlayer ~= plr then
                                targetPlayer = plr
                            end
                            if plr.Character and plr.Character:FindFirstChild("HumanoidRootPart") then
                                status = getPlayerStatus(plr)
                            end
                            break
                        end
                    end
                end
                
                if not shouldStillVoid and targetValid and status == "alive" then
                    voidActive = false
                    autoVoidActive = false
                    notify("void conditions ended", "void", 5)
                    if orbitEnabled then
                        teleporting = false
                        task.wait(0.1)
                        startOrbit()
                    else
                        if orbitStartPosition then
                            humanoidRootPart.Position = orbitStartPosition
                            notify("returned to start", "void", 5)
                        end
                    end
                else
                    humanoidRootPart.Position = Vector3.new(
                        math.random(-999999, 999999),
                        math.random(0, 999999),
                        math.random(-999999, 999999)
                    )
                end
            else
                if not manualVoidEnabled then
                    voidActive = false
                    returnToVoidStartPosition()
                else
                    humanoidRootPart.Position = Vector3.new(
                        math.random(-999999, 999999),
                        math.random(0, 999999),
                        math.random(-999999, 999999)
                    )
                end
            end
            
            task.wait(0.01)
        end
    end)
end

game:GetService("Players").PlayerAdded:Connect(function(plr)
    if lastKnownTargetName and plr.Name == lastKnownTargetName then
        targetPlayer = plr
        lastKnownTarget = plr
        notify("target rejoined", "orbit", 5)
        if orbitEnabled then
            teleporting = false
            task.wait(0.1)
            startOrbit()
        end
    end
end)

game:GetService("Players").PlayerRemoving:Connect(function(plr)
    if plr == targetPlayer or (lastKnownTargetName and plr.Name == lastKnownTargetName) then
        lastKnownTarget = targetPlayer
        lastKnownTargetName = targetPlayer and targetPlayer.Name or lastKnownTargetName
        if targetPlayer and targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
            lastKnownTargetPosition = targetPlayer.Character.HumanoidRootPart.Position
        end
        targetPlayer = nil
        
        if orbitEnabled then
            stopOrbitAndReturn("target left - returning")
        end
    end
end)

while true do
    wait(0.01)
    if isrbxactive() then
        local mouse1 = ismouse1pressed()
        local mPos = Vector2.new(Mouse.X, Mouse.Y)
        
        if Keybind17_IsListening then
            for i = 1, 255 do
                if iskeypressed(i) and not ismouse1pressed() then
                    Keybind17_Key = i
                    Keybind17_IsListening = false
                    local keyName = KeyNames[i] or "Unknown"
                    Keybind17_Text.Text = "[ " .. keyName .. " ]"
                    Keybind17_Text.Color = Color3.fromHex("#ffffff")
                    break
                end
            end
        elseif iskeypressed(Keybind17_Key) and not Keybind22_IsListening and not Keybind29_IsListening and not Keybind30_IsListening then
            orbitEnabled = not orbitEnabled
            Switch12_IsChecked = orbitEnabled
            if orbitEnabled then
                Switch12_IndBorder.Position = Switch12.Position + Vector2.new(15, 1)
                Switch12_Ind.Position = Switch12.Position + Vector2.new(15, 1)
                autoVoidActive = false
                startOrbit()
            else
                Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                teleporting = false
                orbitActive = false
                autoVoidActive = false
                returnToStartPosition()
                orbitStartPosition = nil
            end
            task.wait(0.2)
        end
        
        if Keybind22_IsListening then
            for i = 1, 255 do
                if iskeypressed(i) and not ismouse1pressed() then
                    Keybind22_Key = i
                    Keybind22_IsListening = false
                    local keyName = KeyNames[i] or "Unknown"
                    Keybind22_Text.Text = "[ " .. keyName .. " ]"
                    Keybind22_Text.Color = Color3.fromHex("#ffffff")
                    break
                end
            end
        elseif iskeypressed(Keybind22_Key) and not Keybind17_IsListening and not Keybind29_IsListening and not Keybind30_IsListening then
            manualVoidEnabled = not manualVoidEnabled
            Switch21_IsChecked = manualVoidEnabled
            if manualVoidEnabled then
                Switch21_IndBorder.Position = Switch21.Position + Vector2.new(15, 1)
                Switch21_Ind.Position = Switch21.Position + Vector2.new(15, 1)
                if orbitEnabled then
                    orbitEnabled = false
                    orbitActive = false
                    Switch12_IsChecked = false
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                    teleporting = false
                end
                notify("manual void", "void", 5)
                startVoid(false)
            else
                Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
                Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
                returnToVoidStartPosition()
            end
            task.wait(0.2)
        end
        
        if Keybind29_IsListening then
            for i = 1, 255 do
                if iskeypressed(i) and not ismouse1pressed() then
                    Keybind29_Key = i
                    Keybind29_IsListening = false
                    local keyName = KeyNames[i] or "Unknown"
                    Keybind29_Text.Text = "[ " .. keyName .. " ]"
                    Keybind29_Text.Color = Color3.fromHex("#ffffff")
                    break
                end
            end
        elseif iskeypressed(Keybind29_Key) and not Keybind17_IsListening and not Keybind22_IsListening and not Keybind30_IsListening then
            autoStompEnabled = not autoStompEnabled
            Switch28_IsChecked = autoStompEnabled
            if autoStompEnabled then
                Switch28_IndBorder.Position = Switch28.Position + Vector2.new(15, 1)
                Switch28_Ind.Position = Switch28.Position + Vector2.new(15, 1)
                notify("stomp on", "stomp", 5)
            else
                Switch28_IndBorder.Position = Switch28.Position + Vector2.new(1, 1)
                Switch28_Ind.Position = Switch28.Position + Vector2.new(1, 1)
            end
            task.wait(0.2)
        end
        
        if Keybind30_IsListening then
            for i = 1, 255 do
                if iskeypressed(i) and not ismouse1pressed() then
                    Keybind30_Key = i
                    Keybind30_IsListening = false
                    local keyName = KeyNames[i] or "Unknown"
                    Keybind30_Text.Text = "[ " .. keyName .. " ]"
                    Keybind30_Text.Color = Color3.fromHex("#ffffff")
                    break
                end
            end
        elseif iskeypressed(Keybind30_Key) and not Keybind17_IsListening and not Keybind22_IsListening and not Keybind29_IsListening then
            local newState = not Square1.Visible
            Square1.Visible = newState
            Slider3.Visible = newState
            Slider3_Knob.Visible = newState
            Slider3_ValueText.Visible = newState
            Text5.Visible = newState
            Square8.Visible = newState
            Square8_Border.Visible = newState
            Dropdown9.Visible = newState
            Dropdown9_Text.Visible = newState
            Dropdown9_Arrow.Visible = newState
            for _, item in ipairs(Dropdown9_Items) do
                if item.Box then item.Box.Visible = newState end
                if item.Text then item.Text.Visible = newState end
            end
            Switch12.Visible = newState
            Switch12_Bg.Visible = newState
            Switch12_IndBorder.Visible = newState
            Switch12_Ind.Visible = newState
            Switch12_Label.Visible = newState
            Text13.Visible = newState
            Square14.Visible = newState
            Square14_Border.Visible = newState
            Square15.Visible = newState
            Square15_Border.Visible = newState
            Text16.Visible = newState
            Keybind17.Visible = newState
            Keybind17_Text.Visible = newState
            Switch21.Visible = newState
            Switch21_Bg.Visible = newState
            Switch21_IndBorder.Visible = newState
            Switch21_Ind.Visible = newState
            Switch21_Label.Visible = newState
            Keybind22.Visible = newState
            Keybind22_Text.Visible = newState
            Square23.Visible = newState
            Square23_Border.Visible = newState
            Text24.Visible = newState
            Slider25.Visible = newState
            Slider25_Knob.Visible = newState
            Slider25_ValueText.Visible = newState
            Switch28.Visible = newState
            Switch28_Bg.Visible = newState
            Switch28_IndBorder.Visible = newState
            Switch28_Ind.Visible = newState
            Switch28_Label.Visible = newState
            Keybind29.Visible = newState
            Keybind29_Text.Visible = newState
            Keybind30.Visible = newState
            Keybind30_Text.Visible = newState
            Text31.Visible = newState
            Square32.Visible = newState
            Square32_Border.Visible = newState
            task.wait(0.2)
        end
        
        if mouse1 and not lastMouse1 then
            if Dropdown9.Visible and mPos.X >= Dropdown9.Position.X and mPos.X <= Dropdown9.Position.X + Dropdown9.Size.X and
               mPos.Y >= Dropdown9.Position.Y and mPos.Y <= Dropdown9.Position.Y + Dropdown9.Size.Y then
                pcall(function() onChanged() end)
                local isOpen = Dropdown9_Items[1] and Dropdown9_Items[1].Box.Visible
                if isOpen ~= nil then
                    for _, item in ipairs(Dropdown9_Items) do
                        if item.Box then
                            item.Box.Visible = not isOpen
                            item.Text.Visible = not isOpen
                        end
                    end
                end
            end
            
            if Dropdown9_Items[1] and Dropdown9_Items[1].Box and Dropdown9_Items[1].Box.Visible then
                for _, item in ipairs(Dropdown9_Items) do
                    if item.Box and mPos.X >= item.Box.Position.X and mPos.X <= item.Box.Position.X + item.Box.Size.X and
                       mPos.Y >= item.Box.Position.Y and mPos.Y <= item.Box.Position.Y + item.Box.Size.Y then
                        Dropdown9_Text.Text = item.Value
                        targetPlayer = item.Player
                        lastKnownTarget = targetPlayer
                        lastKnownTargetName = targetPlayer and targetPlayer.Name
                        
                        if targetPlayer and targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
                            lastKnownTargetPosition = targetPlayer.Character.HumanoidRootPart.Position
                        end
                        
                        for _, it in ipairs(Dropdown9_Items) do
                            if it.Box then
                                it.Box.Visible = false
                                it.Text.Visible = false
                            end
                        end
                        if orbitEnabled then
                            teleporting = false
                            orbitActive = false
                            autoVoidActive = false
                            task.wait(0.1)
                            startOrbit()
                        end
                    end
                end
            end
            
            if Switch12_Label.Visible and mPos.X >= Switch12.Position.X and mPos.X <= Switch12.Position.X + Switch12.Size.X and
               mPos.Y >= Switch12.Position.Y and mPos.Y <= Switch12.Position.Y + Switch12.Size.Y then
                Switch12_IsChecked = not Switch12_IsChecked
                orbitEnabled = Switch12_IsChecked
                if Switch12_IsChecked then
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(15, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(15, 1)
                    autoVoidActive = false
                    startOrbit()
                else
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                    teleporting = false
                    orbitActive = false
                    autoVoidActive = false
                    returnToStartPosition()
                    orbitStartPosition = nil
                end
            end
            
            if Switch21_Label.Visible and mPos.X >= Switch21.Position.X and mPos.X <= Switch21.Position.X + Switch21.Size.X and
               mPos.Y >= Switch21.Position.Y and mPos.Y <= Switch21.Position.Y + Switch21.Size.Y then
                Switch21_IsChecked = not Switch21_IsChecked
                manualVoidEnabled = Switch21_IsChecked
                if Switch21_IsChecked then
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(15, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(15, 1)
                    
                    if orbitEnabled then
                        orbitEnabled = false
                        orbitActive = false
                        Switch12_IsChecked = false
                        Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                        Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                        teleporting = false
                    end
                    
                    notify("manual void", "void", 5)
                    startVoid(false)
                else
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
                    returnToVoidStartPosition()
                end
            end
            
            if Switch28_Label.Visible and mPos.X >= Switch28.Position.X and mPos.X <= Switch28.Position.X + Switch28.Size.X and
               mPos.Y >= Switch28.Position.Y and mPos.Y <= Switch28.Position.Y + Switch28.Size.Y then
                Switch28_IsChecked = not Switch28_IsChecked
                autoStompEnabled = Switch28_IsChecked
                if Switch28_IsChecked then
                    Switch28_IndBorder.Position = Switch28.Position + Vector2.new(15, 1)
                    Switch28_Ind.Position = Switch28.Position + Vector2.new(15, 1)
                    notify("stomp on", "stomp", 5)
                else
                    Switch28_IndBorder.Position = Switch28.Position + Vector2.new(1, 1)
                    Switch28_Ind.Position = Switch28.Position + Vector2.new(1, 1)
                end
            end
            
            if Keybind17.Visible and mPos.X >= Keybind17.Position.X and mPos.X <= Keybind17.Position.X + Keybind17.Size.X and
               mPos.Y >= Keybind17.Position.Y and mPos.Y <= Keybind17.Position.Y + Keybind17.Size.Y then
                Keybind17_IsListening = true
                Keybind17_Text.Text = "..."
                Keybind17_Text.Color = Color3.fromHex("#FFFF00")
            end
            
            if Keybind22.Visible and mPos.X >= Keybind22.Position.X and mPos.X <= Keybind22.Position.X + Keybind22.Size.X and
               mPos.Y >= Keybind22.Position.Y and mPos.Y <= Keybind22.Position.Y + Keybind22.Size.Y then
                Keybind22_IsListening = true
                Keybind22_Text.Text = "..."
                Keybind22_Text.Color = Color3.fromHex("#FFFF00")
            end
            
            if Keybind29.Visible and mPos.X >= Keybind29.Position.X and mPos.X <= Keybind29.Position.X + Keybind29.Size.X and
               mPos.Y >= Keybind29.Position.Y and mPos.Y <= Keybind29.Position.Y + Keybind29.Size.Y then
                Keybind29_IsListening = true
                Keybind29_Text.Text = "..."
                Keybind29_Text.Color = Color3.fromHex("#FFFF00")
            end
            
            if Keybind30.Visible and mPos.X >= Keybind30.Position.X and mPos.X <= Keybind30.Position.X + Keybind30.Size.X and
               mPos.Y >= Keybind30.Position.Y and mPos.Y <= Keybind30.Position.Y + Keybind30.Size.Y then
                Keybind30_IsListening = true
                Keybind30_Text.Text = "..."
                Keybind30_Text.Color = Color3.fromHex("#FFFF00")
            end
            
            if Square1.Visible and mPos.X >= Square1.Position.X and mPos.X <= Square1.Position.X + Square1.Size.X and
               mPos.Y >= Square1.Position.Y and mPos.Y <= Square1.Position.Y + Square1.Size.Y then
                dragging = Square1
                dragStart = mPos
                startPos = Square1.Position
            end
            
            if Slider3_Knob.Visible and mPos.X >= Slider3_Knob.Position.X and mPos.X <= Slider3_Knob.Position.X + Slider3_Knob.Size.X and
               mPos.Y >= Slider3_Knob.Position.Y and mPos.Y <= Slider3_Knob.Position.Y + Slider3_Knob.Size.Y then
                dragging = Slider3_Knob
                dragStart = mPos
                startPos = Slider3_Knob.Position
            end
            
            if Slider25_Knob.Visible and mPos.X >= Slider25_Knob.Position.X and mPos.X <= Slider25_Knob.Position.X + Slider25_Knob.Size.X and
               mPos.Y >= Slider25_Knob.Position.Y and mPos.Y <= Slider25_Knob.Position.Y + Slider25_Knob.Size.Y then
                dragging = Slider25_Knob
                dragStart = mPos
                startPos = Slider25_Knob.Position
            end
        end
        
        if not mouse1 and lastMouse1 then
            dragging = nil
        end
        
        if dragging and mouse1 then
            local delta = mPos - dragStart
            dragging.Position = startPos + delta
            if dragging == Slider3_Knob then
                local minX = Slider3.Position.X
                local maxX = Slider3.Position.X + Slider3.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Slider3.Position.Y + 5 - dragging.Size.Y/2)
                local percent = (dragging.Position.X - minX) / (Slider3.Size.X)
                local value = 1 + (30 - 1) * percent
                Slider3_Value = value
                Slider3_ValueText.Text = tostring(math.floor(value)) .. ""
                pcall(function() onChanged(value) end)
            end
            if dragging == Slider25_Knob then
                local minX = Slider25.Position.X
                local maxX = Slider25.Position.X + Slider25.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Slider25.Position.Y + 5 - dragging.Size.Y/2)
                local percent = (dragging.Position.X - minX) / (Slider25.Size.X)
                local value = 0 + (0.1 - 0) * percent
                Slider25_Value = value
                Slider25_ValueText.Text = tostring(math.floor(value)) .. ""
                pcall(function() onChanged(value) end)
            end
            if dragging == Square1 then
                Slider3.Position = dragging.Position + Vector2.new(23, 175.5)
                local percent = (Slider3_Value - 1) / (30 - 1)
                Slider3_Knob.Position = Slider3.Position + Vector2.new(189 * percent - 10, 5 - 10)
                Slider3_ValueText.Position = Slider3.Position + Vector2.new(189/2, -10)
                Text5.Position = dragging.Position + Vector2.new(38, 24)
                Square8.Position = dragging.Position + Vector2.new(18.5, 17)
                Square8_Border.Position = Square8.Position
                Dropdown9.Position = dragging.Position + Vector2.new(12, 203.5)
                Dropdown9_Text.Position = Dropdown9.Position + Vector2.new(5, 8)
                Dropdown9_Arrow.Position = Dropdown9.Position + Vector2.new(205 - 20, 8)
                for i, item in ipairs(Dropdown9_Items) do
                    if item.Box then
                        item.Box.Position = Dropdown9.Position + Vector2.new(0, 32 * i)
                        item.Text.Position = item.Box.Position + Vector2.new(5, 8)
                    end
                end
                Switch12.Position = dragging.Position + Vector2.new(13.5, 280)
                Switch12_Bg.Position = Switch12.Position
                Switch12_Label.Position = Switch12.Position + Vector2.new(50, 5)
                if Switch12_IsChecked then
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(15, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(15, 1)
                else
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                end
                Text13.Position = dragging.Position + Vector2.new(64.5, 134)
                Square14.Position = dragging.Position + Vector2.new(19, 134)
                Square14_Border.Position = Square14.Position
                Square15.Position = dragging.Position + Vector2.new(13.5, 250)
                Square15_Border.Position = Square15.Position
                Text16.Position = dragging.Position + Vector2.new(81, 250)
                Keybind17.Position = dragging.Position + Vector2.new(115.5, 280)
                Keybind17_Text.Position = Keybind17.Position + Vector2.new(100/2, 30/2)
                Switch21.Position = dragging.Position + Vector2.new(12, 321)
                Switch21_Bg.Position = Switch21.Position
                Switch21_Label.Position = Switch21.Position + Vector2.new(50, 5)
                if Switch21_IsChecked then
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(15, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(15, 1)
                else
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
                end
                Keybind22.Position = dragging.Position + Vector2.new(115.5, 321)
                Keybind22_Text.Position = Keybind22.Position + Vector2.new(100/2, 30/2)
                Square23.Position = dragging.Position + Vector2.new(20, 64)
                Square23_Border.Position = Square23.Position
                Text24.Position = dragging.Position + Vector2.new(64.5, 64)
                Slider25.Position = dragging.Position + Vector2.new(25.5, 109.5)
                local percent = (Slider25_Value - 0) / (0.1 - 0)
                Slider25_Knob.Position = Slider25.Position + Vector2.new(189 * percent - 10, 5 - 10)
                Slider25_ValueText.Position = Slider25.Position + Vector2.new(189/2, -10)
                Switch28.Position = dragging.Position + Vector2.new(12, 362)
                Switch28_Bg.Position = Switch28.Position
                Switch28_Label.Position = Switch28.Position + Vector2.new(50, 5)
                if Switch28_IsChecked then
                    Switch28_IndBorder.Position = Switch28.Position + Vector2.new(15, 1)
                    Switch28_Ind.Position = Switch28.Position + Vector2.new(15, 1)
                else
                    Switch28_IndBorder.Position = Switch28.Position + Vector2.new(1, 1)
                    Switch28_Ind.Position = Switch28.Position + Vector2.new(1, 1)
                end
                Keybind29.Position = dragging.Position + Vector2.new(114, 362)
                Keybind29_Text.Position = Keybind29.Position + Vector2.new(100/2, 30/2)
                Keybind30.Position = dragging.Position + Vector2.new(61, 459)
                Keybind30_Text.Position = Keybind30.Position + Vector2.new(100/2, 30/2)
                Text31.Position = dragging.Position + Vector2.new(64.5, 435)
                Square32.Position = dragging.Position + Vector2.new(10, 434)
                Square32_Border.Position = Square32.Position
            end
        end
        
        lastMouse1 = mouse1
    end
end

notify("orbit loaded", "orbit", 5)
