-- Generated by Matcha GUI Builder
local Mouse = game.Players.LocalPlayer:GetMouse()

-- Image Renderer
local function CreateImageGroup(cache, size, startPos)
    local group = {}
    local props = { Visible = true, Transparency = 1, Position = startPos, ZIndex = 1, Size = size, Remove = function() for _, d in ipairs(cache) do d:Remove() end end }
    setmetatable(group, {
        __index = props,
        __newindex = function(t, k, v)
            if k == "Position" then
                local delta = v - props.Position
                props.Position = v
                for _, d in ipairs(cache) do d.Position = d.Position + delta end
            else
                props[k] = v
                if k == "Visible" then for _, d in ipairs(cache) do d.Visible = v end
                elseif k == "Transparency" then for _, d in ipairs(cache) do d.Transparency = v end
                elseif k == "ZIndex" then for _, d in ipairs(cache) do d.ZIndex = v end
                end
            end
        end
    })
    return group
end

local function DrawImage(data, startPos, scaleX, scaleY, zIndex, transparency)
    local cache = {}
    local palette = data.Palette
    local alphas = data.Alpha
    local x, y, w, h, c = data.X, data.Y, data.W, data.H, data.C
    for i = 1, #x do
        local rect = Drawing.new("Square")
        rect.Visible = true
        rect.Transparency = transparency * (alphas[c[i]] or 1)
        rect.ZIndex = zIndex
        rect.Filled = true
        rect.Color = palette[c[i]]
        rect.Size = Vector2.new(w[i] * scaleX, h[i] * scaleY)
        rect.Position = startPos + Vector2.new(x[i] * scaleX, y[i] * scaleY)
        table.insert(cache, rect)
    end
    return cache
end

-- Square1 (Square)
local Square1 = Drawing.new("Square")
Square1.Visible = true
Square1.Transparency = 1
Square1.ZIndex = 10
Square1.Color = Color3.fromHex("#121212")
Square1.Position = Vector2.new(87, 113)
Square1.Size = Vector2.new(235, 439)
Square1.Filled = true
Square1.Corner = 36

-- Slider3 (Slider)
local Slider3 = Drawing.new("Square")
Slider3.Visible = true
Slider3.Transparency = 1
Slider3.Color = Color3.fromHex("#444444")
Slider3.Filled = true
Slider3.Size = Vector2.new(189, 10)
Slider3.Position = Vector2.new(110, 288.5)
Slider3.ZIndex = 20
Slider3.Corner = 18
local Slider3_Value = 15
local Slider3_Knob = Drawing.new("Square")
Slider3_Knob.Visible = true
Slider3_Knob.Transparency = 1
Slider3_Knob.Color = Color3.fromHex("#ffffff")
Slider3_Knob.Filled = true
Slider3_Knob.Size = Vector2.new(20, 20)
Slider3_Knob.Position = Slider3.Position + Vector2.new(189 * ((Slider3_Value - 1) / 29) - 10, 5 - 10)
Slider3_Knob.ZIndex = 21
Slider3_Knob.Corner = 100
local Slider3_ValueText = Drawing.new("Text")
Slider3_ValueText.Visible = true
Slider3_ValueText.Text = tostring(math.floor(Slider3_Value)) .. ""
Slider3_ValueText.Size = 16
Slider3_ValueText.Center = true
Slider3_ValueText.Outline = true
Slider3_ValueText.Color = Color3.new(1, 1, 1)
Slider3_ValueText.Position = Slider3.Position + Vector2.new(189/2, -10)
Slider3_ValueText.ZIndex = 22

-- Text5 (Text)
local Text5 = Drawing.new("Text")
Text5.Visible = true
Text5.Transparency = 1
Text5.ZIndex = 70
Text5.Color = Color3.fromHex("#ffffff")
Text5.Position = Square1.Position + Vector2.new(39, 23)
Text5.Text = "bad dh orbit"
Text5.Size = 29
Text5.Center = false
Text5.Outline = false
Text5.Font = Drawing.Fonts.Minecraft

-- Image7 (Image) - Add your Image7 data here

-- Square8 (Square)
local Square8 = Drawing.new("Square")
Square8.Visible = true
Square8.Transparency = 1
Square8.ZIndex = 30
Square8.Color = Color3.fromHex("#444444")
Square8.Position = Square1.Position + Vector2.new(18.5, 17)
Square8.Size = Vector2.new(203, 39)
Square8.Filled = true
Square8.Corner = 29

-- Intelligent Border for Square8
local Square8_Border = Drawing.new("Square")
Square8_Border.Visible = true
Square8_Border.Transparency = 1
Square8_Border.ZIndex = 31
Square8_Border.Color = Color3.fromHex("#000000")
Square8_Border.Filled = false
Square8_Border.Thickness = 0
Square8_Border.Position = Square8.Position
Square8_Border.Size = Square8.Size
Square8_Border.Corner = 29

-- Dropdown9 (Dropdown)
local Dropdown9 = Drawing.new("Square")
Dropdown9.Visible = true
Dropdown9.Transparency = 1
Dropdown9.Color = Color3.fromHex("#444444")
Dropdown9.Filled = true
Dropdown9.Size = Vector2.new(205, 32)
Dropdown9.Position = Vector2.new(99, 316.5)
Dropdown9.ZIndex = 120
Dropdown9.Corner = 16
local Dropdown9_Text = Drawing.new("Text")
Dropdown9_Text.Visible = true
Dropdown9_Text.Text = "select player (press)"
Dropdown9_Text.Size = 16
Dropdown9_Text.Outline = false
Dropdown9_Text.Font = Drawing.Fonts.UI
Dropdown9_Text.Color = Color3.fromHex("#ffffff")
Dropdown9_Text.Position = Dropdown9.Position + Vector2.new(5, 8)
Dropdown9_Text.ZIndex = 122
local Dropdown9_Arrow = Drawing.new("Text")
Dropdown9_Arrow.Visible = true
Dropdown9_Arrow.Text = "▼"
Dropdown9_Arrow.Size = 12.8
Dropdown9_Arrow.Outline = false
Dropdown9_Arrow.Color = Color3.fromHex("#ffffff")
Dropdown9_Arrow.Position = Dropdown9.Position + Vector2.new(205 - 20, 8)
Dropdown9_Arrow.ZIndex = 122
local Dropdown9_Items = {}

-- Switch12 (Switch)
local Switch12 = Drawing.new("Square")
Switch12.Visible = true
Switch12.Transparency = 1
Switch12.Color = Color3.fromHex("#000000")
Switch12.Thickness = 1
Switch12.Filled = false
Switch12.Size = Vector2.new(40, 26)
Switch12.Position = Vector2.new(100.5, 393)
Switch12.ZIndex = 80
Switch12.Corner = 18
local Switch12_Bg = Drawing.new("Square")
Switch12_Bg.Visible = true
Switch12_Bg.Transparency = 1
Switch12_Bg.Color = Color3.fromHex("#ffffff")
Switch12_Bg.Filled = true
Switch12_Bg.Size = Switch12.Size
Switch12_Bg.Position = Switch12.Position
Switch12_Bg.ZIndex = 80
Switch12_Bg.Corner = 18
local Switch12_IndBorder = Drawing.new("Square")
Switch12_IndBorder.Visible = true
Switch12_IndBorder.Transparency = 1
Switch12_IndBorder.Color = Color3.fromHex("#000000")
Switch12_IndBorder.Thickness = 1
Switch12_IndBorder.Filled = false
Switch12_IndBorder.Size = Vector2.new(24, 24)
Switch12_IndBorder.ZIndex = 82
Switch12_IndBorder.Corner = 18
local Switch12_Ind = Drawing.new("Square")
Switch12_Ind.Visible = true
Switch12_Ind.Transparency = 1
Switch12_Ind.Color = Color3.fromHex("#444444")
Switch12_Ind.Filled = true
Switch12_Ind.Size = Vector2.new(24, 24)
Switch12_Ind.ZIndex = 82
Switch12_Ind.Corner = 18
local Switch12_IsChecked = false
Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
local Switch12_Label = Drawing.new("Text")
Switch12_Label.Visible = true
Switch12_Label.Text = "Orbit"
Switch12_Label.Size = 16
Switch12_Label.Color = Color3.fromHex("#FFFFFF")
Switch12_Label.Outline = true
Switch12_Label.Font = Drawing.Fonts.UI
Switch12_Label.Position = Switch12.Position + Vector2.new(50, 5)
Switch12_Label.ZIndex = 81

-- Switch21 - Manual Void
local Switch21 = Drawing.new("Square")
Switch21.Visible = true
Switch21.Transparency = 1
Switch21.Color = Color3.fromHex("#000000")
Switch21.Thickness = 1
Switch21.Filled = false
Switch21.Size = Vector2.new(40, 26)
Switch21.Position = Vector2.new(100.5, 461)
Switch21.ZIndex = 80
Switch21.Corner = 18
local Switch21_Bg = Drawing.new("Square")
Switch21_Bg.Visible = true
Switch21_Bg.Transparency = 1
Switch21_Bg.Color = Color3.fromHex("#ffffff")
Switch21_Bg.Filled = true
Switch21_Bg.Size = Switch21.Size
Switch21_Bg.Position = Switch21.Position
Switch21_Bg.ZIndex = 80
Switch21_Bg.Corner = 18
local Switch21_IndBorder = Drawing.new("Square")
Switch21_IndBorder.Visible = true
Switch21_IndBorder.Transparency = 1
Switch21_IndBorder.Color = Color3.fromHex("#000000")
Switch21_IndBorder.Thickness = 1
Switch21_IndBorder.Filled = false
Switch21_IndBorder.Size = Vector2.new(24, 24)
Switch21_IndBorder.ZIndex = 82
Switch21_IndBorder.Corner = 18
local Switch21_Ind = Drawing.new("Square")
Switch21_Ind.Visible = true
Switch21_Ind.Transparency = 1
Switch21_Ind.Color = Color3.fromHex("#444444")
Switch21_Ind.Filled = true
Switch21_Ind.Size = Vector2.new(24, 24)
Switch21_Ind.ZIndex = 82
Switch21_Ind.Corner = 18
local Switch21_IsChecked = false
Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
local Switch21_Label = Drawing.new("Text")
Switch21_Label.Visible = true
Switch21_Label.Text = "Manual Void"
Switch21_Label.Size = 16
Switch21_Label.Color = Color3.fromHex("#FFFFFF")
Switch21_Label.Outline = true
Switch21_Label.Font = Drawing.Fonts.UI
Switch21_Label.Position = Switch21.Position + Vector2.new(50, 5)
Switch21_Label.ZIndex = 81

-- Text13 (Text)
local Text13 = Drawing.new("Text")
Text13.Visible = true
Text13.Transparency = 1
Text13.ZIndex = 90
Text13.Color = Color3.fromHex("#FFFFFF")
Text13.Position = Square1.Position + Vector2.new(39, 134)
Text13.Text = "tp distance"
Text13.Size = 19
Text13.Center = false
Text13.Outline = false
Text13.Font = Drawing.Fonts.Minecraft

-- Square14 (Square)
local Square14 = Drawing.new("Square")
Square14.Visible = true
Square14.Transparency = 1
Square14.ZIndex = 40
Square14.Color = Color3.fromHex("#444444")
Square14.Position = Square1.Position + Vector2.new(19, 134)
Square14.Size = Vector2.new(202, 19)
Square14.Filled = true
Square14.Corner = 29

-- Intelligent Border for Square14
local Square14_Border = Drawing.new("Square")
Square14_Border.Visible = true
Square14_Border.Transparency = 1
Square14_Border.ZIndex = 41
Square14_Border.Color = Color3.fromHex("#000000")
Square14_Border.Filled = false
Square14_Border.Thickness = 0
Square14_Border.Position = Square14.Position
Square14_Border.Size = Square14.Size
Square14_Border.Corner = 29

-- Square15 (Square)
local Square15 = Drawing.new("Square")
Square15.Visible = true
Square15.Transparency = 1
Square15.ZIndex = 50
Square15.Color = Color3.fromHex("#444444")
Square15.Position = Square1.Position + Vector2.new(13.5, 250)
Square15.Size = Vector2.new(202, 19)
Square15.Filled = true
Square15.Corner = 29

-- Intelligent Border for Square15
local Square15_Border = Drawing.new("Square")
Square15_Border.Visible = true
Square15_Border.Transparency = 1
Square15_Border.ZIndex = 51
Square15_Border.Color = Color3.fromHex("#000000")
Square15_Border.Filled = false
Square15_Border.Thickness = 0
Square15_Border.Position = Square15.Position
Square15_Border.Size = Square15.Size
Square15_Border.Corner = 29

-- Text16 (Text)
local Text16 = Drawing.new("Text")
Text16.Visible = true
Text16.Transparency = 1
Text16.ZIndex = 100
Text16.Color = Color3.fromHex("#FFFFFF")
Text16.Position = Square1.Position + Vector2.new(39, 250)
Text16.Text = "orbit toggles"
Text16.Size = 18
Text16.Center = false
Text16.Outline = false
Text16.Font = Drawing.Fonts.Minecraft

-- Keybind17 (Keybind)
local Keybind17 = Drawing.new("Square")
Keybind17.Visible = true
Keybind17.Transparency = 1
Keybind17.Color = Color3.fromHex("#444444")
Keybind17.Filled = true
Keybind17.Size = Vector2.new(100, 30)
Keybind17.Position = Vector2.new(202.5, 393)
Keybind17.ZIndex = 110
Keybind17.Corner = 10
local Keybind17_Text = Drawing.new("Text")
Keybind17_Text.Text = "[ X ]"
Keybind17_Text.Size = 16
Keybind17_Text.Center = true
Keybind17_Text.Outline = false
Keybind17_Text.Font = Drawing.Fonts.UI
Keybind17_Text.Color = Color3.fromHex("#ffffff")
Keybind17_Text.Position = Keybind17.Position + Vector2.new(100/2, 30/2)
Keybind17_Text.Visible = true
Keybind17_Text.ZIndex = 112
local Keybind17_Key = 0x58
local Keybind17_IsListening = false

-- Keybind22 (Keybind)
local Keybind22 = Drawing.new("Square")
Keybind22.Visible = true
Keybind22.Transparency = 1
Keybind22.Color = Color3.fromHex("#444444")
Keybind22.Filled = true
Keybind22.Size = Vector2.new(100, 30)
Keybind22.Position = Vector2.new(202.5, 461)
Keybind22.ZIndex = 110
Keybind22.Corner = 10
local Keybind22_Text = Drawing.new("Text")
Keybind22_Text.Text = "[ V ]"
Keybind22_Text.Size = 16
Keybind22_Text.Center = true
Keybind22_Text.Outline = false
Keybind22_Text.Font = Drawing.Fonts.UI
Keybind22_Text.Color = Color3.fromHex("#ffffff")
Keybind22_Text.Position = Keybind22.Position + Vector2.new(100/2, 30/2)
Keybind22_Text.Visible = true
Keybind22_Text.ZIndex = 112
local Keybind22_Key = 0x56
local Keybind22_IsListening = false

-- Square19 (Square)
local Square19 = Drawing.new("Square")
Square19.Visible = true
Square19.Transparency = 1
Square19.ZIndex = 50
Square19.Color = Color3.fromHex("#444444")
Square19.Position = Square1.Position + Vector2.new(13.5, 317)
Square19.Size = Vector2.new(202, 19)
Square19.Filled = true
Square19.Corner = 29

-- Intelligent Border for Square19
local Square19_Border = Drawing.new("Square")
Square19_Border.Visible = true
Square19_Border.Transparency = 1
Square19_Border.ZIndex = 51
Square19_Border.Color = Color3.fromHex("#000000")
Square19_Border.Filled = false
Square19_Border.Thickness = 0
Square19_Border.Position = Square19.Position
Square19_Border.Size = Square19.Size
Square19_Border.Corner = 29

-- Text20 (Text)
local Text20 = Drawing.new("Text")
Text20.Visible = true
Text20.Transparency = 1
Text20.ZIndex = 100
Text20.Color = Color3.fromHex("#FFFFFF")
Text20.Position = Square1.Position + Vector2.new(39, 317)
Text20.Text = "void toggles"
Text20.Size = 18
Text20.Center = false
Text20.Outline = false
Text20.Font = Drawing.Fonts.Minecraft

-- Square23 (Square)
local Square23 = Drawing.new("Square")
Square23.Visible = true
Square23.Transparency = 1
Square23.ZIndex = 40
Square23.Color = Color3.fromHex("#444444")
Square23.Position = Square1.Position + Vector2.new(20, 64)
Square23.Size = Vector2.new(202, 19)
Square23.Filled = true
Square23.Corner = 29

-- Intelligent Border for Square23
local Square23_Border = Drawing.new("Square")
Square23_Border.Visible = true
Square23_Border.Transparency = 1
Square23_Border.ZIndex = 41
Square23_Border.Color = Color3.fromHex("#000000")
Square23_Border.Filled = false
Square23_Border.Thickness = 0
Square23_Border.Position = Square23.Position
Square23_Border.Size = Square23.Size
Square23_Border.Corner = 29

-- Text24 (Text)
local Text24 = Drawing.new("Text")
Text24.Visible = true
Text24.Transparency = 1
Text24.ZIndex = 90
Text24.Color = Color3.fromHex("#FFFFFF")
Text24.Position = Square1.Position + Vector2.new(39, 64)
Text24.Text = "orbit speed"
Text24.Size = 19
Text24.Center = false
Text24.Outline = false
Text24.Font = Drawing.Fonts.Minecraft

-- Slider25 (Slider)
local Slider25 = Drawing.new("Square")
Slider25.Visible = true
Slider25.Transparency = 1
Slider25.Color = Color3.fromHex("#444444")
Slider25.Filled = true
Slider25.Size = Vector2.new(189, 10)
Slider25.Position = Vector2.new(112.5, 222.5)
Slider25.ZIndex = 20
Slider25.Corner = 18
local Slider25_Value = 0.0
local Slider25_Knob = Drawing.new("Square")
Slider25_Knob.Visible = true
Slider25_Knob.Transparency = 1
Slider25_Knob.Color = Color3.fromHex("#ffffff")
Slider25_Knob.Filled = true
Slider25_Knob.Size = Vector2.new(20, 20)
Slider25_Knob.Position = Slider25.Position + Vector2.new(189 * (Slider25_Value / 0.1) - 10, 5 - 10)
Slider25_Knob.ZIndex = 21
Slider25_Knob.Corner = 100
local Slider25_ValueText = Drawing.new("Text")
Slider25_ValueText.Visible = true
Slider25_ValueText.Text = string.format("%.5f", Slider25_Value)
Slider25_ValueText.Size = 16
Slider25_ValueText.Center = true
Slider25_ValueText.Outline = true
Slider25_ValueText.Color = Color3.new(1, 1, 1)
Slider25_ValueText.Position = Slider25.Position + Vector2.new(189/2, -10)
Slider25_ValueText.ZIndex = 22

local targetPlayer = nil
local orbitEnabled = false
local manualVoidEnabled = false
local teleporting = false
local autoVoidActive = false
local player = game:GetService("Players").LocalPlayer
local lastKnownTargetPosition = nil
local lastKnownTarget = nil
local lastUpdate = 0
local dragging = nil
local dragStart = nil
local startPos = nil
local lastMouse1 = false
local voidStartPosition = nil

function speedToPercent(speed)
    local maxSpeed = 0.1
    return speed / maxSpeed
end

function percentToSpeed(percent)
    local maxSpeed = 0.1
    return percent * maxSpeed
end

task.spawn(function()
    while true do
        task.wait(1)
        local dropdownOpen = false
        if Dropdown9_Items[1] and Dropdown9_Items[1].Box then
            dropdownOpen = Dropdown9_Items[1].Box.Visible
        end
        
        if not dropdownOpen then
            for _, item in ipairs(Dropdown9_Items) do
                if item.Box then item.Box:Remove() end
                if item.Text then item.Text:Remove() end
            end
            Dropdown9_Items = {}
            
            local selectBox = Drawing.new("Square")
            selectBox.Visible = false
            selectBox.Transparency = 1
            selectBox.Color = Color3.fromHex("#333333")
            selectBox.Filled = true
            selectBox.Size = Vector2.new(205, 32)
            selectBox.Position = Dropdown9.Position + Vector2.new(0, 32)
            selectBox.ZIndex = 125
            selectBox.Corner = 16
            local selectText = Drawing.new("Text")
            selectText.Visible = false
            selectText.Text = "select player (press)"
            selectText.Size = 16
            selectText.Outline = false
            selectText.Font = Drawing.Fonts.UI
            selectText.Color = Color3.fromHex("#FFFFFF")
            selectText.Position = selectBox.Position + Vector2.new(5, 8)
            selectText.ZIndex = 126
            table.insert(Dropdown9_Items, {Box = selectBox, Text = selectText, Value = "select player (press)"})
            
            for _, plr in ipairs(game:GetService("Players"):GetPlayers()) do
                if plr ~= player then
                    local box = Drawing.new("Square")
                    box.Visible = false
                    box.Transparency = 1
                    box.Color = Color3.fromHex("#333333")
                    box.Filled = true
                    box.Size = Vector2.new(205, 32)
                    box.Position = Dropdown9.Position + Vector2.new(0, 32 * (#Dropdown9_Items + 1))
                    box.ZIndex = 125
                    box.Corner = 16
                    local text = Drawing.new("Text")
                    text.Visible = false
                    text.Text = plr.Name
                    text.Size = 16
                    text.Outline = false
                    text.Font = Drawing.Fonts.UI
                    text.Color = Color3.fromHex("#FFFFFF")
                    text.Position = box.Position + Vector2.new(5, 8)
                    text.ZIndex = 126
                    table.insert(Dropdown9_Items, {Box = box, Text = text, Value = plr.Name, Player = plr})
                end
            end
        end
    end
end)

local KeyNames = {
    [48] = "0", [49] = "1", [50] = "2", [51] = "3", [52] = "4", [53] = "5", [54] = "6", [55] = "7", [56] = "8", [57] = "9",
    [1] = "LeftMouse", [2] = "RightMouse", [4] = "MiddleMouse",
    [8] = "Backspace", [9] = "Tab", [13] = "Enter", [16] = "Shift", [17] = "Ctrl", [18] = "Alt",
    [19] = "Pause", [20] = "CapsLock", [27] = "Esc", [32] = "Space",
    [33] = "PageUp", [34] = "PageDown", [35] = "End", [36] = "Home",
    [37] = "Left", [38] = "Up", [39] = "Right", [40] = "Down",
    [45] = "Insert", [46] = "Delete",
    [65] = "A", [66] = "B", [67] = "C", [68] = "D", [69] = "E", [70] = "F", [71] = "G", [72] = "H", [73] = "I", [74] = "J",
    [75] = "K", [76] = "L", [77] = "M", [78] = "N", [79] = "O", [80] = "P", [81] = "Q", [82] = "R", [83] = "S", [84] = "T",
    [85] = "U", [86] = "V", [87] = "W", [88] = "X", [89] = "Y", [90] = "Z",
    [112] = "F1", [113] = "F2", [114] = "F3", [115] = "F4", [116] = "F5", [117] = "F6", [118] = "F7", [119] = "F8",
    [120] = "F9", [121] = "F10", [122] = "F11", [123] = "F12",
}

function hasSpawnProtection(plr)
    if not plr or not plr.Character then return false end
    local character = plr.Character
    if character:FindFirstChildOfClass("ForceField") then
        return true
    end
    return false
end

function shouldAutoVoid()
    if targetPlayer and hasSpawnProtection(targetPlayer) then
        return true, "spawn protection"
    end
    local character = player.Character
    if character then
        local humanoid = character:FindFirstChild("Humanoid")
        if humanoid and humanoid.Health < 50 then
            return true, "health below 50"
        end
    end
    return false
end

function getRandomOrbitPoint(center, radius)
    local x = (math.random() * 2 - 1) * radius
    local y = (math.random() * 2 - 1) * radius
    local z = (math.random() * 2 - 1) * radius
    return Vector3.new(center.X + x, center.Y + y, center.Z + z)
end

function teleportToTargetTorso()
    if not targetPlayer or not targetPlayer.Character then return end
    local targetPart = targetPlayer.Character:FindFirstChild("HumanoidRootPart")
    if not targetPart then
        targetPart = targetPlayer.Character:FindFirstChild("UpperTorso") or targetPlayer.Character:FindFirstChild("Torso")
    end
    if not targetPart then return end
    
    local character = player.Character
    if not character or not character:FindFirstChild("HumanoidRootPart") then return end
    
    local hrp = character.HumanoidRootPart
    hrp.Position = Vector3.new(targetPart.Position.X, targetPart.Position.Y + 3, targetPart.Position.Z)
end

function startOrbit()
    if not targetPlayer or not targetPlayer.Character or not targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
        orbitEnabled = false
        Switch12_IsChecked = false
        Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
        Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
        return
    end
    
    teleporting = true
    lastKnownTarget = targetPlayer
    local character = player.Character
    if not character or not character:FindFirstChild("HumanoidRootPart") then
        teleporting = false
        return
    end
    
    local humanoidRootPart = character.HumanoidRootPart
    
    task.spawn(function()
        while teleporting and orbitEnabled do
            local targetValid = targetPlayer and targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart")
            local voidReason
            autoVoidActive, voidReason = shouldAutoVoid()
            
            if autoVoidActive then
                teleporting = false
                notify("auto-void: " .. voidReason, "void", 2)
                task.spawn(function()
                    startVoid(true)
                end)
                break
            end
            
            if targetValid then
                local targetHRP = targetPlayer.Character.HumanoidRootPart
                local targetPos = targetHRP.Position
                lastKnownTargetPosition = targetPos
                lastKnownTarget = targetPlayer
                local newPos = getRandomOrbitPoint(targetPos, Slider3_Value)
                humanoidRootPart.Position = newPos
            end
            
            if Slider25_Value <= 0 then
                task.wait()
            else
                task.wait(Slider25_Value)
            end
        end
        
        teleporting = false
    end)
end

function startVoid(isAutoVoid)
    local character = player.Character
    if not character or not character:FindFirstChild("HumanoidRootPart") then
        return
    end
    
    local humanoidRootPart = character.HumanoidRootPart
    if not isAutoVoid then
        voidStartPosition = humanoidRootPart.Position
    end
    
    task.spawn(function()
        local voidActive = true
        
        while voidActive do
            if isAutoVoid then
                local shouldStillVoid, _ = shouldAutoVoid()
                local targetValid = targetPlayer and targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart")
                
                if not shouldStillVoid and targetValid then
                    voidActive = false
                    autoVoidActive = false
                    notify("auto-void ended - resuming orbit", "void", 2)
                    if orbitEnabled then
                        teleporting = false
                        task.wait(0.1)
                        startOrbit()
                    end
                else
                    humanoidRootPart.Position = Vector3.new(
                        math.random(-999999, 999999),
                        math.random(0, 999999),
                        math.random(-999999, 999999)
                    )
                end
            else
                if not manualVoidEnabled then
                    voidActive = false
                    if voidStartPosition then
                        humanoidRootPart.Position = voidStartPosition
                        voidStartPosition = nil
                    end
                else
                    humanoidRootPart.Position = Vector3.new(
                        math.random(-999999, 999999),
                        math.random(0, 999999),
                        math.random(-999999, 999999)
                    )
                end
            end
            
            task.wait(0.01)
        end
    end)
end

game:GetService("Players").PlayerAdded:Connect(function(plr)
    if lastKnownTarget and plr.Name == lastKnownTarget.Name then
        targetPlayer = plr
        lastKnownTarget = plr
        notify("target rejoined: " .. plr.Name, "orbit", 2)
        if orbitEnabled then
            teleporting = false
            task.wait(0.1)
            startOrbit()
        end
    end
end)

game:GetService("Players").PlayerRemoving:Connect(function(plr)
    if plr == targetPlayer then
        lastKnownTarget = targetPlayer
        if targetPlayer and targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
            lastKnownTargetPosition = targetPlayer.Character.HumanoidRootPart.Position
        end
        targetPlayer = nil
    end
end)

while true do
    task.wait(0.01)
    if isrbxactive() then
        local mouse1 = ismouse1pressed()
        local mPos = Vector2.new(Mouse.X, Mouse.Y)
        
        if Keybind17_IsListening then
            for i = 1, 255 do
                if iskeypressed(i) and not ismouse1pressed() then
                    Keybind17_Key = i
                    Keybind17_IsListening = false
                    local keyName = KeyNames[i] or "Unknown"
                    Keybind17_Text.Text = "[ " .. keyName .. " ]"
                    Keybind17_Text.Color = Color3.fromHex("#ffffff")
                    break
                end
            end
        elseif iskeypressed(Keybind17_Key) and not Keybind22_IsListening then
            orbitEnabled = not orbitEnabled
            Switch12_IsChecked = orbitEnabled
            if orbitEnabled then
                Switch12_IndBorder.Position = Switch12.Position + Vector2.new(15, 1)
                Switch12_Ind.Position = Switch12.Position + Vector2.new(15, 1)
                autoVoidActive = false
                startOrbit()
            else
                Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                teleporting = false
                autoVoidActive = false
                teleportToTargetTorso()
            end
            task.wait(0.2)
        end
        
        if Keybind22_IsListening then
            for i = 1, 255 do
                if iskeypressed(i) and not ismouse1pressed() then
                    Keybind22_Key = i
                    Keybind22_IsListening = false
                    local keyName = KeyNames[i] or "Unknown"
                    Keybind22_Text.Text = "[ " .. keyName .. " ]"
                    Keybind22_Text.Color = Color3.fromHex("#ffffff")
                    break
                end
            end
        elseif iskeypressed(Keybind22_Key) and not Keybind17_IsListening then
            manualVoidEnabled = not manualVoidEnabled
            Switch21_IsChecked = manualVoidEnabled
            if manualVoidEnabled then
                Switch21_IndBorder.Position = Switch21.Position + Vector2.new(15, 1)
                Switch21_Ind.Position = Switch21.Position + Vector2.new(15, 1)
                if orbitEnabled then
                    orbitEnabled = false
                    Switch12_IsChecked = false
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                    teleporting = false
                end
                notify("manual void activated", "manual void", 2)
                startVoid(false)
            else
                Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
                Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
            end
            task.wait(0.2)
        end
        
        if mouse1 and not lastMouse1 then
            if Dropdown9.Visible and mPos.X >= Dropdown9.Position.X and mPos.X <= Dropdown9.Position.X + Dropdown9.Size.X and
               mPos.Y >= Dropdown9.Position.Y and mPos.Y <= Dropdown9.Position.Y + Dropdown9.Size.Y then
                local isOpen = Dropdown9_Items[1] and Dropdown9_Items[1].Box.Visible
                for _, item in ipairs(Dropdown9_Items) do
                    if item.Box then
                        item.Box.Visible = not isOpen
                        item.Text.Visible = not isOpen
                    end
                end
            end
            
            if Dropdown9_Items[1] and Dropdown9_Items[1].Box and Dropdown9_Items[1].Box.Visible then
                for _, item in ipairs(Dropdown9_Items) do
                    if item.Box and mPos.X >= item.Box.Position.X and mPos.X <= item.Box.Position.X + item.Box.Size.X and
                       mPos.Y >= item.Box.Position.Y and mPos.Y <= item.Box.Position.Y + item.Box.Size.Y then
                        Dropdown9_Text.Text = item.Value
                        targetPlayer = item.Player
                        lastKnownTarget = targetPlayer
                        
                        if targetPlayer and targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
                            lastKnownTargetPosition = targetPlayer.Character.HumanoidRootPart.Position
                        end
                        
                        for _, it in ipairs(Dropdown9_Items) do
                            if it.Box then
                                it.Box.Visible = false
                                it.Text.Visible = false
                            end
                        end
                        if orbitEnabled then
                            teleporting = false
                            autoVoidActive = false
                            task.wait(0.1)
                            startOrbit()
                        end
                    end
                end
            end
            
            if Switch12.Visible and mPos.X >= Switch12.Position.X and mPos.X <= Switch12.Position.X + Switch12.Size.X and
               mPos.Y >= Switch12.Position.Y and mPos.Y <= Switch12.Position.Y + Switch12.Size.Y then
                Switch12_IsChecked = not Switch12_IsChecked
                orbitEnabled = Switch12_IsChecked
                if Switch12_IsChecked then
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(15, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(15, 1)
                    autoVoidActive = false
                    startOrbit()
                else
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                    teleporting = false
                    autoVoidActive = false
                    teleportToTargetTorso()
                end
            end
            
            if Switch21.Visible and mPos.X >= Switch21.Position.X and mPos.X <= Switch21.Position.X + Switch21.Size.X and
               mPos.Y >= Switch21.Position.Y and mPos.Y <= Switch21.Position.Y + Switch21.Size.Y then
                Switch21_IsChecked = not Switch21_IsChecked
                manualVoidEnabled = Switch21_IsChecked
                if Switch21_IsChecked then
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(15, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(15, 1)
                    
                    if orbitEnabled then
                        orbitEnabled = false
                        Switch12_IsChecked = false
                        Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                        Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                        teleporting = false
                    end
                    
                    notify("manual void activated", "manual void", 2)
                    startVoid(false)
                else
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
                end
            end
            
            if Keybind17.Visible and mPos.X >= Keybind17.Position.X and mPos.X <= Keybind17.Position.X + Keybind17.Size.X and
               mPos.Y >= Keybind17.Position.Y and mPos.Y <= Keybind17.Position.Y + Keybind17.Size.Y then
                Keybind17_IsListening = true
                Keybind17_Text.Text = "..."
                Keybind17_Text.Color = Color3.fromHex("#FFFF00")
            end
            
            if Keybind22.Visible and mPos.X >= Keybind22.Position.X and mPos.X <= Keybind22.Position.X + Keybind22.Size.X and
               mPos.Y >= Keybind22.Position.Y and mPos.Y <= Keybind22.Position.Y + Keybind22.Size.Y then
                Keybind22_IsListening = true
                Keybind22_Text.Text = "..."
                Keybind22_Text.Color = Color3.fromHex("#FFFF00")
            end
            
            if Square1.Visible and mPos.X >= Square1.Position.X and mPos.X <= Square1.Position.X + Square1.Size.X and
               mPos.Y >= Square1.Position.Y and mPos.Y <= Square1.Position.Y + Square1.Size.Y then
                dragging = Square1
                dragStart = mPos
                startPos = Square1.Position
            end
            
            if Slider3_Knob.Visible and mPos.X >= Slider3_Knob.Position.X and mPos.X <= Slider3_Knob.Position.X + Slider3_Knob.Size.X and
               mPos.Y >= Slider3_Knob.Position.Y and mPos.Y <= Slider3_Knob.Position.Y + Slider3_Knob.Size.Y then
                dragging = Slider3_Knob
                dragStart = mPos
                startPos = Slider3_Knob.Position
            end
            
            if Slider25_Knob.Visible and mPos.X >= Slider25_Knob.Position.X and mPos.X <= Slider25_Knob.Position.X + Slider25_Knob.Size.X and
               mPos.Y >= Slider25_Knob.Position.Y and mPos.Y <= Slider25_Knob.Position.Y + Slider25_Knob.Size.Y then
                dragging = Slider25_Knob
                dragStart = mPos
                startPos = Slider25_Knob.Position
            end
        end
        
        if not mouse1 and lastMouse1 then
            dragging = nil
        end
        
        if dragging and mouse1 then
            local delta = mPos - dragStart
            dragging.Position = startPos + delta
            
            if dragging == Slider3_Knob then
                local minX = Slider3.Position.X
                local maxX = Slider3.Position.X + Slider3.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Slider3.Position.Y + 5 - dragging.Size.Y/2)
                
                local percent = (dragging.Position.X - minX) / Slider3.Size.X
                Slider3_Value = 1 + (30 - 1) * percent
                Slider3_ValueText.Text = tostring(math.floor(Slider3_Value)) .. ""
            end
            
            if dragging == Slider25_Knob then
                local minX = Slider25.Position.X
                local maxX = Slider25.Position.X + Slider25.Size.X
                if dragging.Position.X < minX then dragging.Position = Vector2.new(minX, dragging.Position.Y) end
                if dragging.Position.X > maxX then dragging.Position = Vector2.new(maxX, dragging.Position.Y) end
                dragging.Position = Vector2.new(dragging.Position.X, Slider25.Position.Y + 5 - dragging.Size.Y/2)
                
                local percent = (dragging.Position.X - minX) / Slider25.Size.X
                Slider25_Value = percentToSpeed(percent)
                Slider25_ValueText.Text = string.format("%.5f", Slider25_Value)
            end
            
            if dragging == Square1 then
                Slider3.Position = dragging.Position + Vector2.new(23, 175.5)
                local percent = (Slider3_Value - 1) / 29
                Slider3_Knob.Position = Slider3.Position + Vector2.new(189 * percent - 10, 5 - 10)
                Slider3_ValueText.Position = Slider3.Position + Vector2.new(189/2, -10)
                
                Text5.Position = dragging.Position + Vector2.new(39, 23)
                Square8.Position = dragging.Position + Vector2.new(18.5, 17)
                Square8_Border.Position = Square8.Position
                
                Dropdown9.Position = dragging.Position + Vector2.new(12, 203.5)
                Dropdown9_Text.Position = Dropdown9.Position + Vector2.new(5, 8)
                Dropdown9_Arrow.Position = Dropdown9.Position + Vector2.new(205 - 20, 8)
                for i, item in ipairs(Dropdown9_Items) do
                    if item.Box then
                        item.Box.Position = Dropdown9.Position + Vector2.new(0, 32 * i)
                        item.Text.Position = item.Box.Position + Vector2.new(5, 8)
                    end
                end
                
                Switch12.Position = dragging.Position + Vector2.new(13.5, 280)
                Switch12_Bg.Position = Switch12.Position
                Switch12_Label.Position = Switch12.Position + Vector2.new(50, 5)
                if Switch12_IsChecked then
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(15, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(15, 1)
                else
                    Switch12_IndBorder.Position = Switch12.Position + Vector2.new(1, 1)
                    Switch12_Ind.Position = Switch12.Position + Vector2.new(1, 1)
                end
                
                Keybind17.Position = dragging.Position + Vector2.new(115.5, 280)
                Keybind17_Text.Position = Keybind17.Position + Vector2.new(100/2, 30/2)
                
                Switch21.Position = dragging.Position + Vector2.new(13.5, 348)
                Switch21_Bg.Position = Switch21.Position
                Switch21_Label.Position = Switch21.Position + Vector2.new(50, 5)
                if Switch21_IsChecked then
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(15, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(15, 1)
                else
                    Switch21_IndBorder.Position = Switch21.Position + Vector2.new(1, 1)
                    Switch21_Ind.Position = Switch21.Position + Vector2.new(1, 1)
                end
                
                Keybind22.Position = dragging.Position + Vector2.new(115.5, 348)
                Keybind22_Text.Position = Keybind22.Position + Vector2.new(100/2, 30/2)
                
                Text13.Position = dragging.Position + Vector2.new(39, 134)
                Square14.Position = dragging.Position + Vector2.new(19, 134)
                Square14_Border.Position = Square14.Position
                Square15.Position = dragging.Position + Vector2.new(13.5, 250)
                Square15_Border.Position = Square15.Position
                Text16.Position = dragging.Position + Vector2.new(39, 250)
                Square19.Position = dragging.Position + Vector2.new(13.5, 317)
                Square19_Border.Position = Square19.Position
                Text20.Position = dragging.Position + Vector2.new(39, 317)
                Square23.Position = dragging.Position + Vector2.new(20, 64)
                Square23_Border.Position = Square23.Position
                Text24.Position = dragging.Position + Vector2.new(39, 64)
                Slider25.Position = dragging.Position + Vector2.new(25.5, 109.5)
                percent = speedToPercent(Slider25_Value)
                Slider25_Knob.Position = Slider25.Position + Vector2.new(189 * percent - 10, 5 - 10)
                Slider25_ValueText.Position = Slider25.Position + Vector2.new(189/2, -10)
                
                -- Image7.Position = dragging.Position + Vector2.new(13.5, 387)
            end
        end
        
        lastMouse1 = mouse1
    end
end

notify("orbit script loaded - auto-void active", "orbit", 5)
